### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by Kulitorum** [MatterHackers/MatterSlice#10]
1>------ Build started: Project: MatterSlice, Configuration: Debug Any CPU ------
1>C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(1697,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "nunit.framework". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
1>C:\Users\mic_000\Downloads\MatterSlice-master\UnitTests\BridgeTests.cs(37,7,37,12): error CS0246: The type or namespace name 'NUnit' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\mic_000\Downloads\MatterSlice-master\UnitTests\TestUtlities.cs(38,7,38,12): error CS0246: The type or namespace name 'NUnit' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\mic_000\Downloads\MatterSlice-master\UnitTests\SettingsTests.cs(38,7,38,12): error CS0246: The type or namespace name 'NUnit' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\mic_000\Downloads\MatterSlice-master\UnitTests\SlicingTests.cs(38,7,38,12): error CS0246: The type or namespace name 'NUnit' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\mic_000\Downloads\MatterSlice-master\UnitTests\BridgeTests.cs(47,10,47,14): error CS0246: The type or namespace name 'Test' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\mic_000\Downloads\MatterSlice-master\UnitTests\BridgeTests.cs(47,10,47,14): error CS0246: The type or namespace name 'TestAttribute' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\mic_000\Downloads\MatterSlice-master\UnitTests\BridgeTests.cs(44,6,44,17): error CS0246: The type or namespace name 'TestFixture' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\mic_000\Downloads\MatterSlice-master\UnitTests\BridgeTests.cs(44,6,44,17): error CS0246: The type or namespace name 'TestFixtureAttribute' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\mic_000\Downloads\MatterSlice-master\UnitTests\SettingsTests.cs(98,10,98,14): error CS0246: The type or namespace name 'Test' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\mic_000\Downloads\MatterSlice-master\UnitTests\SettingsTests.cs(98,10,98,14): error CS0246: The type or namespace name 'TestAttribute' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\mic_000\Downloads\MatterSlice-master\UnitTests\SettingsTests.cs(108,10,108,14): error CS0246: The type or namespace name 'Test' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\mic_000\Downloads\MatterSlice-master\UnitTests\SettingsTests.cs(108,10,108,14): error CS0246: The type or namespace name 'TestAttribute' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\mic_000\Downloads\MatterSlice-master\UnitTests\SettingsTests.cs(117,10,117,14): error CS0246: The type or namespace name 'Test' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\mic_000\Downloads\MatterSlice-master\UnitTests\SettingsTests.cs(117,10,117,14): error CS0246: The type or namespace name 'TestAttribute' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\mic_000\Downloads\MatterSlice-master\UnitTests\SettingsTests.cs(42,6,42,17): error CS0246: The type or namespace name 'TestFixture' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\mic_000\Downloads\MatterSlice-master\UnitTests\SettingsTests.cs(42,6,42,17): error CS0246: The type or namespace name 'TestFixtureAttribute' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\mic_000\Downloads\MatterSlice-master\UnitTests\SlicingTests.cs(45,10,45,14): error CS0246: The type or namespace name 'Test' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\mic_000\Downloads\MatterSlice-master\UnitTests\SlicingTests.cs(45,10,45,14): error CS0246: The type or namespace name 'TestAttribute' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\mic_000\Downloads\MatterSlice-master\UnitTests\SlicingTests.cs(74,10,74,14): error CS0246: The type or namespace name 'Test' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\mic_000\Downloads\MatterSlice-master\UnitTests\SlicingTests.cs(74,10,74,14): error CS0246: The type or namespace name 'TestAttribute' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\mic_000\Downloads\MatterSlice-master\UnitTests\SlicingTests.cs(42,6,42,17): error CS0246: The type or namespace name 'TestFixture' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\mic_000\Downloads\MatterSlice-master\UnitTests\SlicingTests.cs(42,6,42,17): error CS0246: The type or namespace name 'TestFixtureAttribute' could not be found (are you missing a using directive or an assembly reference?)
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by jlewin** [comment]
The MatterSlice.csproj assumes that it's installed side-by-side with the Agg project and has its Nunit assembly reference pointed at: ..\agg-sharp\AggTests\nunit.framework.dll. 

If you'd like to build MatterSlice independently you can download the Nunit assembly we normally reference from https://github.com/MatterHackers/agg-sharp/blob/master/AggTests/nunit.framework.dll and replace the existing project reference or try swapping it out with a NuGet package.
