### ISSUE TITLE
Infill overshoot

### ISSUE THREAD

**Issue by duisenberg** [MatterHackers/MatterSlice#150]
In some cases infill overshoots the perimeter, even if set to very low overlap:

![image1](https://cloud.githubusercontent.com/assets/21085153/20860315/6aa5aa2e-b975-11e6-920e-c3bc27498b58.jpg)
![image2](https://cloud.githubusercontent.com/assets/21085153/20860316/701888be-b975-11e6-8c15-4309e6342ba3.jpg)
[Knob1.txt](https://github.com/MatterHackers/MatterSlice/files/628931/Knob1.txt)

The txt file contains the STL, Mattercontrol Version 1.6.1.7967

**Comment by larsbrubaker** [comment]
Thank you for the report.

Can you export and attach as a zip your profile. It is not required but will be helpful.

**Comment by duisenberg** [comment]
[Printer.txt](https://github.com/MatterHackers/MatterSlice/files/633286/Printer.txt)

Sorry, I always search the "export printer profile" menu item. Github atm rejects zips. Well ... txt works.

**Comment by duisenberg** [comment]
Since the issue didnt happen again since 1.7 I guess this one can be closed.
