### ISSUE TITLE
Support without Brim

### ISSUE THREAD

**Issue by duisenberg** [MatterHackers/MatterSlice#151]
The brim (first layer expansion) setting from priming does not create a brim for the support towers.

The attached images outlines this, as well as the issue with creating support inside the model where it should only create support from build plate. 

![image2](https://cloud.githubusercontent.com/assets/21085153/21048876/d9aacf76-be11-11e6-97a7-cdbc3011559d.jpg)

STL is the small  Dodeca from http://www.thingiverse.com/thing:1453733 (which prints well without support though)

IMHO a separate brim setting for support - as lines, positive and negative - would be ideal to have control over the support "foorprint".

**Comment by unlimitedbacon** [comment]
Related issue https://github.com/MatterHackers/MatterSlice/issues/66
