### ISSUE TITLE
Expand Thin Walls causes blobs in the side of this print

### ISSUE THREAD

**Issue by unlimitedbacon** [MatterHackers/MatterSlice#156]
This part has 0.3 mm thick walls. When printed with a 0.5 mm nozzle and Expand Thin Wall turned on, many blobs are created in the sides of the walls.

[Original forum post](https://forums.matterhackers.com/topic/403/poor-slicing-performance-after-1-6-upgrade/3)

![1482388289296-capture](https://cloud.githubusercontent.com/assets/3131268/21460482/a883d2c0-c8fd-11e6-8cd2-d020fa97a922.jpg)

[STL and Printer Profile](https://github.com/MatterHackers/MatterSlice/files/671311/BlobIssue.zip)

**Comment by larsbrubaker** [comment]
We have some strange math problems rendering certain features. Dose this also happen while printing?

**Comment by unlimitedbacon** [comment]
Not sure. The same artifacts show up in gcode.ws, but it shows them as travel moves.

**Comment by FireflyNJ** [comment]
Printing walls thinner then the nozzle size?  I wouldn't expect that to work.

**Comment by unlimitedbacon** [comment]
Its definitely not just a rendering error

![img_20170201_123230](https://cloud.githubusercontent.com/assets/3131268/22525899/0e349844-e87e-11e6-9783-bac379e13410.jpg)

**Comment by larsbrubaker** [comment]
Will look into improving this.
