### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by viniciusmiguel** [MatterHackers/MatterSlice#16]
With the emergence of new high performance materials for 3D printing increasingly has been difficult for lay users to configure the correct temperatures for different types of materials, we also know that the materials require different temperatures for different print speeds, and it causes a lot of difference in the outcome of printing.
So I suggest the creation of a feature that allows the inclusion of a temperature table versus speed and the slicer follow this table for cutting. With this we hadware manufacturers we can optimize our mechanics in order to achieve excellence in print quality, and can create Presets temperatures of our materials and deliver it to customers to ease them.

Vinicius Miguel
CNC Brasil

**Comment by larsbrubaker** [comment]
Our preferred method of addressing this is by making profiles in MatterControl.
