### ISSUE TITLE
Make sure all perimeter start points matches 0th perimeter start as best as possible

### ISSUE THREAD

**Issue by larsbrubaker** [MatterHackers/MatterSlice#161]

**Comment by larsbrubaker** [comment]
![2017-01-16 12_58_27-matterhackers_ mattercontrol 1 6](https://cloud.githubusercontent.com/assets/1158332/21998748/8f79d0da-dbeb-11e6-9be7-bb8fd5d35537.png)

Entered on the left but should have got to the top.

**Comment by jlewin** [comment]
Should be fixed in master
