### ISSUE TITLE
Cura is not an reimplementation of Skeinforge

### ISSUE THREAD

**Issue by nallath** [MatterHackers/MatterSlice#17]
Your description states that Cura is a reimplementation of Skeinforge. This is not the case, it was built from scratch.

**Comment by larsbrubaker** [comment]
Hey Nallath, it was my understanding that diad was inspired by and ported / re-wrote much of the code from skeinforge. CuraEngine is an amazing project and one the I am incredibly happy to have been able to port to c#. If diad feels that I miss represented his efforts, he should know that I am incredibly thankful for his work, and do not wish to do anything but say, thank you to him. He is an amazing programmer and has done incredible work to help the 3D printing community.
