### ISSUE TITLE
Minimum retraction distance is ignored

### ISSUE THREAD

**Issue by unlimitedbacon** [MatterHackers/MatterSlice#180]
Here I have the Minimum Travel Requiring Retraction set to 4 mm, yet when it moves from the perimeters to the infill, a retraction is performed. This distance less than 4 mm.

![screenshot from 2017-01-27 11-54-39](https://cloud.githubusercontent.com/assets/3131268/22385452/8e2ec95c-e487-11e6-91fc-d528679fdb8f.png)

[RetractDistance.zip](https://github.com/MatterHackers/MatterSlice/files/736143/RetractDistance.zip)

**Comment by larsbrubaker** [comment]
Fixed (in my test)
