### ISSUE TITLE
Material for object changes when I turn on support

### ISSUE THREAD

**Issue by FireflyNJ** [MatterHackers/MatterSlice#214]
I set object to use second Material and it is correctly shown in blue on layer view.  When I turn on supports which is material one, the object also becomes material one. layer view shows both support and object in black.   but it works fine oposite way, object on material 1 and support as materal 2.
MatterControl 1.7/MatterSlice

edit:   I think I was suppose to post its in MatterControl, not MatterSlice,   close this if not correct.

**Comment by larsbrubaker** [comment]
Thanks. We only need this in one place (either would be good). I'll keep it in MatterControl.
