### ISSUE TITLE
Wipe tower printed twice on every layer

### ISSUE THREAD

**Issue by unlimitedbacon** [MatterHackers/MatterSlice#216]
This issue was reported by a customer. I have confirmed that it is happening on 1.7.0 stable and experimental.

> It seems to be printing the purge tower twice. A layer's worth of printing (after the first layer) goes like this:
> 
> Ext 0 lays down its wipe spiral
> Ext 0 lays down its portion of the part
> Extruder switch to 1
> Ext 1 lays down its wipe spiral, making a complete solid layer of the wipe tower
> Ext 1 lays down its portion of the part
> Extruder switch back to 0
> Ext 0 lays another wipe spiral without moving up a layer
> Extruder switch to 1, but this time the hot end moves slowly as it returns to the print area
> Ext 1 lays another wipe spiral, again without moving up a layer
> Extruder switch
> Next layer

[Example G-Code](https://github.com/MatterHackers/MatterSlice/files/945122/cubeslice1.1.zip)

**Comment by larsbrubaker** [comment]
Addressed.

This is happening when we have support turned on and are doing a wipe tower. The new code will not double draw the wipe tower. It goes to it with each layer required including when doing air gap layers. So, the tower is drawn extruders * 2 times without overlap. However, the new code does sometimes draw one extra time switch.

No support works like it did before, which was correct already.
