### ISSUE TITLE
"First Layer Expansion Loops" overlap first layer support

### ISSUE THREAD

**Issue by wadesherman** [MatterHackers/MatterSlice#218]
On first layers, if the "First Layer Expansion Loops" are wider than the Support "X and Y Distance" they will overlap on the same layer.

1.6.0.8003 on OSX

**Comment by unlimitedbacon** [comment]
Please update to 1.7. This has [already been fixed](https://github.com/MatterHackers/MatterSlice/issues/66).

**Comment by wadesherman** [comment]
cool, thanks. I will change to the alpha update channel.

I did see that issue, but "brim" isn't a matterControl term so I wasn't sure.
