### ISSUE TITLE
Request: Cylindrical wipe tower option

### ISSUE THREAD

**Issue by teejaydub** [MatterHackers/MatterSlice#295]
For dual extruders to work, SO many things have to be perfect. One of them is that your wipe tower has to not come detached from the build plate and wander into your main object!

I've noticed that when this happens, it's most likely to start at a corner of the wipe tower (just like many objects will first peel up at their corners). So, I think a cylindrical wipe tower would reduce the probability of wipe-tower-related casualties.

**Comment by teejaydub** [comment]
Cool, that's great! The link didn't work - maybe it's a private repo? - but I'll look for that. Thanks.

**Comment by larsbrubaker** [comment]
This is fixed in code and will be in the next build (should be mid April)
