### ISSUE TITLE
Start/stop of inner perimeter loops is causing artifacts on the outside

### ISSUE THREAD

**Issue by unlimitedbacon** [MatterHackers/MatterSlice#344]
![img_20180807_153716](https://user-images.githubusercontent.com/3131268/43806727-0a7e6cf4-9a5a-11e8-8a2a-6319bb661f89.jpg)

These artifacts are all over the outside of this print. The gcode shows that these are caused by the start/stop of the inner perimeter loops (not the outer loops). The pause for the retraction at the end of the inner loop is causing a small blob, which overlaps the outer loop.

I think we should consider using the same seam hiding techniques as the outer loop on the inner loops.

![screenshot at 2018-08-07 15-55-14](https://user-images.githubusercontent.com/3131268/43807011-5cbe02da-9a5b-11e8-82ce-432960e051f2.png)
![screenshot at 2018-08-07 15-56-15](https://user-images.githubusercontent.com/3131268/43807013-5f8724c4-9a5b-11e8-91fa-4d57de152269.png)
![screenshot at 2018-08-07 15-56-50](https://user-images.githubusercontent.com/3131268/43807017-62336d68-9a5b-11e8-8e8e-fb2b2023ea29.png)

**Comment by ishapiro** [comment]
I am seeing the same issue when printing to a Monoprice Dela Mini from MatterControl 2.19.17.

I have verified that this is a slicing issue by slicing the same model in Cura 4.1 and then printing the g-code from MatterControl.  This prints without artifacts.
