### ISSUE TITLE
Support interface layers should not be printed at initial layer speed

### ISSUE THREAD

**Issue by unlimitedbacon** [MatterHackers/MatterSlice#350]
Right now the support interface layers are being printed at the initial layer speed. In my case this is 15 mm/s. This causes them to droop a lot. These should either be printed at the bridging speed or the support material speed.

Ideally, I think these should be treated as bridges the same way we are now doing the lowest solid top layers.

![2018-08-16 11_19_00-matterhackers_ mattercontrol 2 0 - experimental - 64bit](https://user-images.githubusercontent.com/3131268/44227039-840c9580-a146-11e8-9d68-5f06a8e1fdc5.png)

**Comment by larsbrubaker** [comment]
I changed this to print at support speed. Please let me know (file another issue) if you want them at bridging speed.
