### ISSUE TITLE
Bridging creates velocity painting effect on entire layer

### ISSUE THREAD

**Issue by jlewin** [MatterHackers/MatterSlice#378]
@cope413 commented on [Tue Sep 11 2018](https://github.com/MatterHackers/MCCentral/issues/4120)

Because bridging speed is applied to all perimeters, not just the area being bridged, layer looks different from rest of the part.

Simplify slows down a few mm before the bridge, and speeds back up a few mm past it.

**Comment by larsbrubaker** [comment]
fixed
