### ISSUE TITLE
Loop start/end optimizations only applied to interior insets

### ISSUE THREAD

**Issue by jlewin** [MatterHackers/MatterSlice#49]
![image](https://cloud.githubusercontent.com/assets/175113/15441198/5acbf0ea-1e8e-11e6-9c1f-93c2248a43fe.png)

**Comment by larsbrubaker** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/1158332/33527515-3220dd52-d807-11e7-8875-bddbe18ad293.png)
