### ISSUE TITLE
Loop start/end optimizations truncate small inner inset edges

### ISSUE THREAD

**Issue by jlewin** [MatterHackers/MatterSlice#50]
![image](https://cloud.githubusercontent.com/assets/175113/15441792/bab5492c-1e91-11e6-9bd7-2a3a5c18c5ca.png)

**Comment by larsbrubaker** [comment]
We remove a maximum of one point.

![image](https://user-images.githubusercontent.com/1158332/33527552-b2d9ec5e-d807-11e7-819c-ad1c129c5035.png)
