### ISSUE TITLE
-d settings.ini throws exception

### ISSUE THREAD

**Issue by MrnB** [MatterHackers/MatterSlice#535]
Issue is linked to #256 However, in this issue 256 a user gets an error when trying to use a config file with -c. In this case, just using -d gives excepton.

When you add '-d' to the commandArgs, application throws an exception when one of the settings is of type Int64 => System.NotImplementedException: 'unknown type 'Int64''

This is because the type Int64 is not mentioned in ConfigSettings.cs as a case in the switch (property.PropertyType.Name). When adding the "Int64" in the first case, also the "Matrix4X4" needs to be added, otherwise still an exception is thrown.

**Comment by larsbrubaker** [comment]
Thanks for the report and the fix.
