### ISSUE TITLE
Finish work on thin wall support

### ISSUE THREAD

**Issue by larsbrubaker** [MatterHackers/MatterSlice#65]
@larsbrubaker commented on [Fri Jun 24 2016](https://github.com/MatterHackers/MatterControl/issues/1020)

**Comment by larsbrubaker** [comment]
Good image in #64 of the problem. 
Also have test models in MatterSlice\SampleSTLs\ThinWalls.stl

**Comment by unlimitedbacon** [comment]
We received two related posts in the forum today:
http://forums.matterhackers.com/topic/256/not-printing-thin-walls
http://forums.matterhackers.com/topic/257/infill-doesn-t-work-0-7-nozzle
