### ISSUE TITLE
Support with extruder 2 is printed twice

### ISSUE THREAD

**Issue by unlimitedbacon** [MatterHackers/MatterSlice#67]
[Slice Settings, STL, and GCode](https://github.com/MatterHackers/MatterSlice/files/340067/SupportPrintedTwice.zip)

When support is being printed with the second extruder, it gets printed twice. This does not happen when a section of the print is also being done with the second extruder.

**Comment by larsbrubaker** [comment]
Closed - fixed.
Please re-open if this is still a problem.
